services:

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql

  order-service:
    build: ./order-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql

  payment-service:
    build: ./payment-service
    ports:
      - "8088:8088"
    depends_on:
      - mysql

  tracking-service:
    build: ./tracking-service
    ports:
      - "8084:8084"
    depends_on:
      - mysql

  gudang-service:
    build: ./gudang-service
    ports:
      - "8085:8085"
    depends_on:
      - mysql

  courier-service:
    build: ./courier-service
    ports:
      - "8086:8086"
    depends_on:
      - mysql

  report-service:
    build: ./report-service
    ports:
      - "8087:8087"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql-tubes
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tubesdb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
